[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SingularIntegralEquations = "e094c991-5a90-5477-8896-c1e4c9552a1a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[sources.SingularIntegralEquations]
path = "SingularIntegralEquations"
