[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
